query GetAuthor {
  author(where: { slug: "donald-silveira" }) {
    name
    slug
    jobTitle
    intro
    picture {
      url
    }
    socials(orderBy: createdAt_ASC) {
      title
      slug
      url
    }
  }
}
