query GetPosts($limit: Int) {
  posts(orderBy: createdAt_DESC, first: $limit) {
    slug
    title
    copy
    coverImage {
      url(transformation: { image: { resize: { fit: scale, width: 550 } } })
    }
    publishedAt
    createdAt
  }
}

query GetPostsSlug {
  posts(orderBy: publishedAt_DESC, first: 10) {
    slug
  }
}

query GetPost($slug: String!) {
  post(where: { slug: $slug }) {
    slug
    title
    copy
    content
    tags
    coverImage {
      url(
        transformation: {
          image: { resize: { fit: scale, width: 1200, height: 600 } }
        }
      )
    }
    authors(first: 1) {
      name
      picture {
        url(transformation: { image: { resize: { height: 50, width: 50 } } })
      }
    }
    createdAt
    updatedAt
  }
}
