query GetProjects($limit: Int) {
  projects(orderBy: order_ASC, first: $limit) {
    slug
    title
    subtitle
    description
    tags
    publishedAt
    image {
      url(transformation: { image: { resize: { fit: scale, width: 600 } } })
    }
  }
}
